// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: messages.proto

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pingpong_PingStorage_FullMethodName = "/messages.Pingpong/PingStorage"
)

// PingpongClient is the client API for Pingpong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingpongClient interface {
	PingStorage(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type pingpongClient struct {
	cc grpc.ClientConnInterface
}

func NewPingpongClient(cc grpc.ClientConnInterface) PingpongClient {
	return &pingpongClient{cc}
}

func (c *pingpongClient) PingStorage(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, Pingpong_PingStorage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingpongServer is the server API for Pingpong service.
// All implementations must embed UnimplementedPingpongServer
// for forward compatibility
type PingpongServer interface {
	PingStorage(context.Context, *Ping) (*Pong, error)
	mustEmbedUnimplementedPingpongServer()
}

// UnimplementedPingpongServer must be embedded to have forward compatible implementations.
type UnimplementedPingpongServer struct {
}

func (UnimplementedPingpongServer) PingStorage(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingStorage not implemented")
}
func (UnimplementedPingpongServer) mustEmbedUnimplementedPingpongServer() {}

// UnsafePingpongServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingpongServer will
// result in compilation errors.
type UnsafePingpongServer interface {
	mustEmbedUnimplementedPingpongServer()
}

func RegisterPingpongServer(s grpc.ServiceRegistrar, srv PingpongServer) {
	s.RegisterService(&Pingpong_ServiceDesc, srv)
}

func _Pingpong_PingStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingpongServer).PingStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pingpong_PingStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingpongServer).PingStorage(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

// Pingpong_ServiceDesc is the grpc.ServiceDesc for Pingpong service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pingpong_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Pingpong",
	HandlerType: (*PingpongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingStorage",
			Handler:    _Pingpong_PingStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
