// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: messages.proto

package messages

import (
	_ "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adresa string `protobuf:"bytes,1,opt,name=adresa,proto3" json:"adresa,omitempty"`
	Port   int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Ime    string `protobuf:"bytes,3,opt,name=ime,proto3" json:"ime,omitempty"`
	Port2  int32  `protobuf:"varint,4,opt,name=port2,proto3" json:"port2,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *Ping) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Ping) GetIme() string {
	if x != nil {
		return x.Ime
	}
	return ""
}

func (x *Ping) GetPort2() int32 {
	if x != nil {
		return x.Port2
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adrese []string `protobuf:"bytes,1,rep,name=adrese,proto3" json:"adrese,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetAdrese() []string {
	if x != nil {
		return x.Adrese
	}
	return nil
}

type NoviArtikli struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artikli []*Proizvod `protobuf:"bytes,1,rep,name=artikli,proto3" json:"artikli,omitempty"`
}

func (x *NoviArtikli) Reset() {
	*x = NoviArtikli{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoviArtikli) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoviArtikli) ProtoMessage() {}

func (x *NoviArtikli) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoviArtikli.ProtoReflect.Descriptor instead.
func (*NoviArtikli) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *NoviArtikli) GetArtikli() []*Proizvod {
	if x != nil {
		return x.Artikli
	}
	return nil
}

type Proizvod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifikator string `protobuf:"bytes,1,opt,name=identifikator,proto3" json:"identifikator,omitempty"`
	Kolcicina     int32  `protobuf:"varint,2,opt,name=kolcicina,proto3" json:"kolcicina,omitempty"`
	Cena          string `protobuf:"bytes,3,opt,name=cena,proto3" json:"cena,omitempty"`
}

func (x *Proizvod) Reset() {
	*x = Proizvod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proizvod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proizvod) ProtoMessage() {}

func (x *Proizvod) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proizvod.ProtoReflect.Descriptor instead.
func (*Proizvod) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Proizvod) GetIdentifikator() string {
	if x != nil {
		return x.Identifikator
	}
	return ""
}

func (x *Proizvod) GetKolcicina() int32 {
	if x != nil {
		return x.Kolcicina
	}
	return 0
}

func (x *Proizvod) GetCena() string {
	if x != nil {
		return x.Cena
	}
	return ""
}

type ArtikalPorucen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId  string `protobuf:"bytes,1,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	Identifikator  string `protobuf:"bytes,2,opt,name=identifikator,proto3" json:"identifikator,omitempty"`
	Nazivskladista string `protobuf:"bytes,3,opt,name=nazivskladista,proto3" json:"nazivskladista,omitempty"`
	Kolicina       int32  `protobuf:"varint,4,opt,name=kolicina,proto3" json:"kolicina,omitempty"`
}

func (x *ArtikalPorucen) Reset() {
	*x = ArtikalPorucen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtikalPorucen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtikalPorucen) ProtoMessage() {}

func (x *ArtikalPorucen) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtikalPorucen.ProtoReflect.Descriptor instead.
func (*ArtikalPorucen) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ArtikalPorucen) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ArtikalPorucen) GetIdentifikator() string {
	if x != nil {
		return x.Identifikator
	}
	return ""
}

func (x *ArtikalPorucen) GetNazivskladista() string {
	if x != nil {
		return x.Nazivskladista
	}
	return ""
}

func (x *ArtikalPorucen) GetKolicina() int32 {
	if x != nil {
		return x.Kolicina
	}
	return 0
}

type DostavaOdSuppliera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId     string      `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	NazivSkladista string      `protobuf:"bytes,2,opt,name=naziv_skladista,json=nazivSkladista,proto3" json:"naziv_skladista,omitempty"`
	Stavke         []*Proizvod `protobuf:"bytes,3,rep,name=stavke,proto3" json:"stavke,omitempty"`
}

func (x *DostavaOdSuppliera) Reset() {
	*x = DostavaOdSuppliera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DostavaOdSuppliera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DostavaOdSuppliera) ProtoMessage() {}

func (x *DostavaOdSuppliera) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DostavaOdSuppliera.ProtoReflect.Descriptor instead.
func (*DostavaOdSuppliera) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DostavaOdSuppliera) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *DostavaOdSuppliera) GetNazivSkladista() string {
	if x != nil {
		return x.NazivSkladista
	}
	return ""
}

func (x *DostavaOdSuppliera) GetStavke() []*Proizvod {
	if x != nil {
		return x.Stavke
	}
	return nil
}

type PorudzbinaZaSuppliera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NazivSkladista string      `protobuf:"bytes,1,opt,name=naziv_skladista,json=nazivSkladista,proto3" json:"naziv_skladista,omitempty"`
	Stavke         []*Proizvod `protobuf:"bytes,2,rep,name=stavke,proto3" json:"stavke,omitempty"` //datum?
}

func (x *PorudzbinaZaSuppliera) Reset() {
	*x = PorudzbinaZaSuppliera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PorudzbinaZaSuppliera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorudzbinaZaSuppliera) ProtoMessage() {}

func (x *PorudzbinaZaSuppliera) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorudzbinaZaSuppliera.ProtoReflect.Descriptor instead.
func (*PorudzbinaZaSuppliera) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *PorudzbinaZaSuppliera) GetNazivSkladista() string {
	if x != nil {
		return x.NazivSkladista
	}
	return ""
}

func (x *PorudzbinaZaSuppliera) GetStavke() []*Proizvod {
	if x != nil {
		return x.Stavke
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0b, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x64, 0x72, 0x65, 0x73, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x64, 0x72, 0x65, 0x73, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f,
	0x72, 0x74, 0x32, 0x22, 0x1e, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x64, 0x72, 0x65, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x64, 0x72,
	0x65, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x4e, 0x6f, 0x76, 0x69, 0x41, 0x72, 0x74, 0x69, 0x6b,
	0x6c, 0x69, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x6b, 0x6c, 0x69, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x69, 0x7a, 0x76, 0x6f, 0x64, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x6b, 0x6c, 0x69,
	0x22, 0x62, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x69, 0x7a, 0x76, 0x6f, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x6b, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x6f, 0x6c, 0x63, 0x69, 0x63, 0x69, 0x6e, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x6f, 0x6c, 0x63, 0x69, 0x63, 0x69, 0x6e, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x6e, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x65, 0x6e, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x6b, 0x61, 0x6c,
	0x50, 0x6f, 0x72, 0x75, 0x63, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x6b, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x6b, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x61, 0x7a, 0x69, 0x76, 0x73, 0x6b, 0x6c, 0x61,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x61, 0x7a,
	0x69, 0x76, 0x73, 0x6b, 0x6c, 0x61, 0x64, 0x69, 0x73, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x6e, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6b,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x6e, 0x61, 0x22, 0x8a, 0x01, 0x0a, 0x12, 0x44, 0x6f, 0x73, 0x74,
	0x61, 0x76, 0x61, 0x4f, 0x64, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x6e, 0x61, 0x7a, 0x69, 0x76, 0x5f, 0x73, 0x6b, 0x6c, 0x61, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x61, 0x7a, 0x69, 0x76, 0x53,
	0x6b, 0x6c, 0x61, 0x64, 0x69, 0x73, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x76,
	0x6b, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x69, 0x7a, 0x76, 0x6f, 0x64, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x76, 0x6b, 0x65, 0x22, 0x6c, 0x0a, 0x15, 0x50, 0x6f, 0x72, 0x75, 0x64, 0x7a, 0x62, 0x69,
	0x6e, 0x61, 0x5a, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x61, 0x12, 0x27, 0x0a,
	0x0f, 0x6e, 0x61, 0x7a, 0x69, 0x76, 0x5f, 0x73, 0x6b, 0x6c, 0x61, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x61, 0x7a, 0x69, 0x76, 0x53, 0x6b, 0x6c,
	0x61, 0x64, 0x69, 0x73, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x76, 0x6b, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x69, 0x7a, 0x76, 0x6f, 0x64, 0x52, 0x06, 0x73, 0x74, 0x61, 0x76,
	0x6b, 0x65, 0x32, 0x3b, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2f,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x1a, 0x0e, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x61, 0x74, 0x32, 0x33, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_messages_proto_goTypes = []interface{}{
	(*Ping)(nil),                  // 0: messages.Ping
	(*Pong)(nil),                  // 1: messages.Pong
	(*NoviArtikli)(nil),           // 2: messages.NoviArtikli
	(*Proizvod)(nil),              // 3: messages.Proizvod
	(*ArtikalPorucen)(nil),        // 4: messages.ArtikalPorucen
	(*DostavaOdSuppliera)(nil),    // 5: messages.DostavaOdSuppliera
	(*PorudzbinaZaSuppliera)(nil), // 6: messages.PorudzbinaZaSuppliera
}
var file_messages_proto_depIdxs = []int32{
	3, // 0: messages.NoviArtikli.artikli:type_name -> messages.Proizvod
	3, // 1: messages.DostavaOdSuppliera.stavke:type_name -> messages.Proizvod
	3, // 2: messages.PorudzbinaZaSuppliera.stavke:type_name -> messages.Proizvod
	0, // 3: messages.Pingpong.PingStorage:input_type -> messages.Ping
	1, // 4: messages.Pingpong.PingStorage:output_type -> messages.Pong
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoviArtikli); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proizvod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtikalPorucen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DostavaOdSuppliera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PorudzbinaZaSuppliera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
